language: php
php:
 - 7.3.5

services:
 - pgsql

install:
 - composer install
 - php bin/console doctrine:database:create
 - php bin/console doctrine:schema:create
 - php bin/console doctrine:fixtures:load

